version: "3.9"
services: 
    django_server: 
        container_name: django_backend
        build: ./django_backend
        ports: 
          - "8000:8000"
        links:
          - redis
    redis:
        image: redis:7
        ports:
          - "6379:6379"
    frontend_react:
        container_name: react_frontend
        build: ./react_frontend
        ports:
          - "3000:3000"