# Generated by Django 4.2.4 on 2023-08-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=50)),
                ('creationTimestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creationTimestamp'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=20)),
                ('avatarPath', models.CharField(max_length=50)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='websocket.lobby')),
            ],
        ),
    ]
