# Generated by Django 4.2.4 on 2023-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0003_lobby_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobbyOwnerToken',
            field=models.TextField(default='0000000', max_length=50),
        ),
    ]
