# Generated by Django 4.2.4 on 2023-08-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0004_lobby_lobbyownertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='endArticle',
            field=models.TextField(default='Pet'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='language',
            field=models.TextField(default='en'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='startArticle',
            field=models.TextField(default='Pet_door'),
        ),
    ]
