# Generated by Django 4.2.4 on 2023-08-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0005_lobby_endarticle_lobby_language_lobby_startarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='language',
            new_name='lang',
        ),
    ]
