# Generated by Django 4.2.4 on 2023-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0006_rename_language_lobby_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
