# Generated by Django 4.2.4 on 2023-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0008_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
