# Generated by Django 4.2.4 on 2023-09-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0009_pagevisit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='endTimer',
            field=models.IntegerField(default=30),
        ),
    ]
