# Generated by Django 4.2.4 on 2024-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0010_lobby_endtimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
